### ISSUE TITLE
Ruby Capstone Project - Kanban Board Review

### ISSUE THREAD

**Issue by NitBravoA92** [NitBravoA92/catalog-of-my-things#36]
# ⭐Kanban Board - Request a Review 👨‍💻

## Project details 📃

- Link the Kanban Board: https://github.com/NitBravoA92/catalog-of-my-things/projects/1
- Number of group members: **Two (3) members**:  @NitBravoA92 @Dachrono @HFG43 
- @NitBravoA92: Team Member 1
- @HFG43: Team Member 2
- @Dachrono: Team Member 3

# To the Reviewer

💝 We really thank 🙇‍♂️ you, dear reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check this Kanban board 🧾 .

We kindly ask 🙏 dear reviewer 🤵 that if there is any kind of issue 🦯 in this Kanban board, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some issues are essential to be changed ♻️ please kindly contact 📞 us through Zoom or Slack, We are available on Microverse UTC-6 time zone.

**Comment by Owusu-Desmond** [comment]
Hi @NitBravoA92 @HFG43 @Dachrono 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 Great working on the set up the of project kanban board :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure that your card [Add unit tests for all implemented methods. Team member 3](https://github.com/NitBravoA92/catalog-of-my-things/issues/30) has the number of points in the [Xpt] prefix. :pray: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Reem-lab** [comment]
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights


- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the Kanban board🤩
- [ ] Amazing working on the cards ⭐





## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
